
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/azimbabu/config-repository
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          search-paths: catalog-service, order-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  application:
    name: config-service
server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: configprops, env, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true
    os:
      enabled: true
    java:
      enabled: true
logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"